version: '3'

services:
  docker_mysql:
    image: mysql:5.7
    command: --max_allowed_packet=6000000
    ports:
      - ${MYSQL_PORT}:3306
    hostname: mysql.${DOMAIN}
    restart: "no"
    volumes:
      - ./energy_data.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  docker_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: docker_mysql